feature_extract_enable : 0
point_filter_num : 2
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.3
cube_side_length : 20
debug : 0
grid_size : 40
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
cam_fx: 447.5147576292463
cam_fy: 447.7186850105169
cam_cx: 297.34290828535893
cam_cy: 263.33217568440745

common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/imu"

preprocess:
    lidar_type: 1 # Livox Avia LiDAR
    scan_line: 6
    blind: 5 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    fov_degree:    120
    extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

camera:
    # img_topic: /usb_cam/image_raw
    # img_topic:  /camera/image_color
    img_topic: "/images"
    #xiyuan
    Rcl: [-0.0330231,-0.000973921,0.999454,
          0.0229059,-0.999738,-0.000217359,
          0.999192,0.0228862,0.0330367]
    Pcl: [0.300069, -0.0258995, -0.141599]
